<?php

/**
 * @file
 *   Provides a UI for the system_settings API functionality.
 */

/**
 * Implements hook_menu().
 */
function system_settings_ui_menu() {
  $items['admin/config/system-settings'] = array(
    'title' => 'System Settings',
    'description' => 'Configure System Settings.',
    'position' => 'right',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system_settings_ui.admin.inc',
  );
  $items['admin/config/system-settings/backends'] = array(
    'title' => 'System Settings Backends',
    'description' => 'Initialize and manage other System Settings backends.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('system_settings_api_initialize_db_form'),
    'weight' => -10,
    'access arguments' => array('administer system_settings backends'),
    'file' => 'system_settings_ui.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_perm().
 */
function hook_permission() {
  $perm =  array(
    'administer system_settings backends'
  );
  return $perm;
}

/**
 * Implements hook_theme().
 */
function system_settings_ui_theme() {
  $path = drupal_get_path('theme', 'system_settings_ui') . '/theme';
  return array(
    'system_settings_ui_database_info' => array(
      'template' => 'settings-php-info',
      'path' => $path,
    ),
  );
}


/**
 * Migrates settings stored in the variables table to system_settings.
 */
function system_settings_ui_migrate_variables_table() {
  // Get the global configuration so that we can record
  global $conf;
  // Get the global user object for our watchdog entry
  global $user;
  $settings = array();
  foreach ($conf as $name => $value) {
    $settings[] = array(
      'name' => $name,
      'value' => $value,
      'modules' => 'system',
      'groups' => 'variables',
    );
  }
  $description = t('User !username imported all of the legacy variables from the variables table into the system_settings api.', array('!username' => l($user->name, 'user/' . $user->uid)));
  system_settings_set_multiple($settings, $description);
}

